# Unless explicitly stated otherwise all files in this repository are dual-licensed
# under the Apache 2.0 or BSD3 Licenses.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2022 Datadog, Inc.
#FROM python:3
FROM python:3.11-slim
ENV DD_SERVICE="notes"
ENV DD_ENV="dev"
ENV DD_VERSION="0.1.0"
ENV DD_LOGS_INJECTION="true"
LABEL com.datadoghq.tags.service="notes"
LABEL com.datadoghq.tags.env="dev"
LABEL com.datadoghq.tags.version="0.1.0"
WORKDIR /home
COPY requirements.txt /home
COPY notes_app /home/notes_app

RUN pip install --no-cache-dir -r requirements.txt
# Run the application with Datadog
CMD ["ddtrace-run", "python", "-m", "notes_app.app"]
# Run with gunicorn in production
#CMD ["ddtrace-run", "gunicorn", "-b", "0.0.0.0:8080", "notes.app:app"]

